language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --omit=*/site-packages/*,*/tests/* -m pytest
after_success:
  coveralls
  